---
- name: reload apparmor profiles  # noqa: command-instead-of-module
  ansible.builtin.command: systemctl reload-or-restart apparmor
  changed_when: true
  failed_when: false

# NOTE: GRUB/initramfs/reboot handlers are centralized in common/handlers/main.yml
# This role notifies "update grub" which triggers the handler chain there
# DO NOT duplicate the "update grub" handler here - it will shadow the common handler
