---
- name: reload apparmor profiles
  ansible.builtin.command: systemctl reload apparmor
- name: update grub
  ansible.builtin.command: update-grub
- name: reboot required
  ansible.builtin.set_fact:
    ansible_reboot_required: true
