---
- name: reload apparmor profiles
  ansible.builtin.command: systemctl reload-or-restart apparmor
  changed_when: true
  failed_when: false

- name: update grub
  ansible.builtin.command: update-grub
  changed_when: true

- name: reboot required
  ansible.builtin.set_fact:
    ansible_reboot_required: true
