---
- name: reload apparmor profiles
  ansible.builtin.systemd:
    name: apparmor
    state: reloaded

- name: update grub
  ansible.builtin.command: update-grub
  changed_when: true

- name: reboot required
  ansible.builtin.set_fact:
    ansible_reboot_required: true
