---
galaxy_info:
  role_name: mariadb
  author: hetzner-secure-infrastructure
  description: MariaDB database server role for WordPress
  license: MIT
  min_ansible_version: "2.12"

  platforms:
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - mariadb
    - database
    - mysql
    - wordpress

dependencies: []
