---
# Node Exporter Role - Service Management Tasks

- name: Node Exporter | Service | Enable and start Node Exporter
  ansible.builtin.systemd:
    name: prometheus-node-exporter
    enabled: true
    state: started
    daemon_reload: true
  tags: [node-exporter, service]
