---
# Common Role - Cleanup Tasks

- name: Common | Cleanup | Remove unnecessary packages
  ansible.builtin.apt:
    name: "{{ common_packages_to_remove }}"
    state: absent
    purge: true
  when: common_cleanup_enabled
  tags: [common, security, cleanup]
