---
# AppArmor Role - Validation Tasks

- name: AppArmor | Validate | Check AppArmor status
  ansible.builtin.command: "{{ apparmor_status_command }}"
  register: apparmor_status
  changed_when: false
  failed_when: false
  tags: [apparmor, status, validate, molecule-notest]

- name: AppArmor | Validate | Display AppArmor status
  ansible.builtin.debug:
    var: apparmor_status.stdout_lines
  when: apparmor_status.rc == 0
  tags: [apparmor, status, validate, molecule-notest]
