---
# Fail2ban Role - Installation Tasks

- name: Fail2Ban | Install | Install Fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: true
  tags: [fail2ban, packages]
