---
# Firewall Role - Installation Tasks

- name: Firewall | Install | Install UFW
  module_defaults:
    ansible.builtin.apt:
      state: present
      update_cache: true
  block:
    - name: Firewall | Install | Install UFW package
      ansible.builtin.apt:
        name: "{{ firewall_apt_packages }}"
      tags: [firewall, packages]
