---
# Firewall Role - Installation Tasks

- name: Firewall | Install | Install UFW
  when: ansible_os_family == 'Debian'
  block:
    - name: Firewall | Install | Install UFW package
      ansible.builtin.apt:
        name: "{{ firewall_apt_packages }}"
        state: present
        update_cache: true
      tags: [firewall, packages]
