---
# OpenBao Role - Handlers

- name: restart openbao
  ansible.builtin.systemd:
    name: openbao
    state: restarted
    daemon_reload: true
  tags: [openbao]
- name: reload openbao
  ansible.builtin.systemd:
    name: openbao
    state: reloaded
  tags: [openbao]
