---
# Node Exporter Role - Handlers

- name: restart node-exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
    daemon_reload: true
  tags: [node-exporter]
- name: reload node-exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: reloaded
  tags: [node-exporter]
