---
# Node Exporter Role - Debian/Ubuntu Specific Variables

# Package Dependencies for Debian-based systems
node_exporter_apt_dependencies:
  - apt-transport-https
  - software-properties-common
  - wget
  - gpg

# GPG Key URL for Debian repository
node_exporter_gpg_key_url: https://s3.amazonaws.com/deb.robustperception.io/41EFC99D.gpg

# Installation method for Debian systems
node_exporter_install_method: apt

# System paths (Debian standard)
node_exporter_install_dir: /usr/local/bin
node_exporter_textfile_dir: /var/lib/node_exporter/textfile_collector
