---
# Prometheus Role - Service Management Tasks

- name: Prometheus | Service | Enable and start Prometheus service
  ansible.builtin.systemd:
    name: prometheus
    enabled: true
    state: started
    daemon_reload: true
  tags: [prometheus, service]
