---
# Nginx WordPress Role - Debian/Ubuntu Specific Variables

# Nginx packages
nginx_wordpress_nginx_packages:
  - nginx
  - nginx-common

# PHP packages
nginx_wordpress_php_packages:
  - "php{{ nginx_wordpress_php_version }}-fpm"
  - "php{{ nginx_wordpress_php_version }}-mysql"
  - "php{{ nginx_wordpress_php_version }}-curl"
  - "php{{ nginx_wordpress_php_version }}-gd"
  - "php{{ nginx_wordpress_php_version }}-mbstring"
  - "php{{ nginx_wordpress_php_version }}-xml"
  - "php{{ nginx_wordpress_php_version }}-xmlrpc"
  - "php{{ nginx_wordpress_php_version }}-zip"
  - "php{{ nginx_wordpress_php_version }}-imagick"

# Additional tools
nginx_wordpress_tools_packages:
  - curl
  - unzip
  - wget

# Certbot (DNS-01 via Cloudflare)
nginx_wordpress_certbot_packages:
  - certbot
  - python3-certbot-dns-cloudflare

# Service names
nginx_wordpress_nginx_service: nginx
nginx_wordpress_php_fpm_service: "php{{ nginx_wordpress_php_version }}-fpm"

# Paths
nginx_wordpress_nginx_config_dir: /etc/nginx
nginx_wordpress_nginx_sites_available: /etc/nginx/sites-available
nginx_wordpress_nginx_sites_enabled: /etc/nginx/sites-enabled
nginx_wordpress_php_fpm_config_dir: "/etc/php/{{ nginx_wordpress_php_version }}/fpm"
nginx_wordpress_php_fpm_pool_dir: "/etc/php/{{ nginx_wordpress_php_version }}/fpm/pool.d"
nginx_wordpress_nginx_repo_key_url: "https://nginx.org/keys/nginx_signing.key"
nginx_wordpress_nginx_repo_keyring_path: "/etc/apt/keyrings/nginx.asc"
nginx_wordpress_nginx_repo_arch: "amd64"
nginx_wordpress_nginx_repo_filename: "nginx-official"
nginx_wordpress_nginx_repo_pin_priority: "900"

# WP-CLI
nginx_wordpress_wpcli_url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
nginx_wordpress_wpcli_path: /usr/local/bin/wp
