---
# Grafana Role - Handlers

- name: restart grafana
  ansible.builtin.systemd:
    name: grafana-server
    state: restarted
    daemon_reload: true
  tags: [grafana]
- name: reload grafana
  ansible.builtin.systemd:
    name: grafana-server
    state: reloaded
  tags: [grafana]
