---
# Nginx WordPress Role - Handlers

- name: reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
  tags: [nginx]
- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
  tags: [nginx]
- name: restart php-fpm
  ansible.builtin.systemd:
    name: php{{ php_version }}-fpm
    state: restarted
  tags: [php]
- name: reload php-fpm
  ansible.builtin.systemd:
    name: php{{ php_version }}-fpm
    state: reloaded
  tags: [php]
